import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <header>
          <div className="container flex items-center justify-between py-4 px-6 mx-auto">
            <Link href="/" className="font-bold text-xl">Job Compass</Link>
            <nav className = "flex gap-2 *:py-4 *:px-4 *:rounded-md">
              <Link href={'/login'} className="bg-gray-200">Login</Link>
              <Link href={'/new-listing'} className="bg-black text-white">Post New Job</Link>
            </nav>
          </div>
        </header> 
        {children}
      </body>
    </html>
  );
}
